import type { Metadata } from 'next';
import { Gowun_Dodum, Jua } from 'next/font/google';
import './globals.css';

const jua = Jua({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${jua.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
